Make get-orig-source non-interactive
* Add a README with basic instructions for obtaining the source version
* fail early if run directly
* using `repo init` sets git config globally, so preserve user's config
* additionally, support using the packaging specific name/email
* shellcheck tar command

diff --git a/debian/scripts/get-orig-source b/debian/scripts/get-orig-source
--- a/debian/scripts/get-orig-source
+++ b/debian/scripts/get-orig-source
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
 
-# Must be invoked by `debian/rules` for the use of `DEB_*` variables
-
 set -e
+
+# Must be invoked by `debian/rules` for the use of `DEB_*` variables
+if ! test -v DEB_VERSION_UPSTREAM; then
+  echo 'usage: debian/rules get-orig-source'
+  exit 1
+fi
 
 mkdir --parents debian/tmp/get-orig-source/manifest
 (
@@ -12,10 +16,31 @@ mkdir --parents debian/tmp/get-orig-source/manifest
   git add default.xml
   git commit --no-gpg-sign --message=Changes
 )
+
+# repo edits(!) a hardcoded ~/.gitconfig which will override ~/.config/git/config
+(
+  if test -f ~/.gitconfig; then
+    echo 'backing up ~/.gitconfig'
+    cp --archive ~/.gitconfig ~/.gitconfig.get-orig-source
+  else
+    touch ~/.gitconfig
+  fi
+
+  git config --global user.name "${DEBFULLNAME:-$(git config user.name)}"
+  git config --global user.email "${DEBEMAIL:-$(git config user.email)}"
+  git config --global color.ui >/dev/null || git config --global color.ui auto
+)
+
 mkdir --parents debian/tmp/get-orig-source/archive
 (
   cd debian/tmp/get-orig-source/archive
   repo init --manifest-url=file://"$(readlink --canonicalize-existing ../manifest/.git)" --depth=1
   repo sync
-  tar --create --xz --file ../../../../../${DEB_SOURCE}_${DEB_VERSION_UPSTREAM}.orig.tar.xz --exclude-from=../../../orig.excludes --mtime=2000-01-01 --sort=name *
+  tar --create --xz --file "../../../../../${DEB_SOURCE}_${DEB_VERSION_UPSTREAM}.orig.tar.xz" --exclude-from=../../../orig.excludes --mtime=2000-01-01 --sort=name ./*
 )
+
+# cleanup
+rm ~/.gitconfig
+if test -f ~/.gitconfig.get-orig-source; then
+  mv ~/.gitconfig.get-orig-source ~/.gitconfig
+fi
